name: pandora
description: Pandora is Dart DI framework.
version: 0.0.1
author: Haris Kovačević <programmerguy92@gmail.com>
homepage: https://github.com/harisk92/blocx_flutter/

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"




